[package]
name = "trollsourie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mouce = { version = "0.2.44", features = ["cli"] }
mouse_position = "0.1.3"
